### ISSUE TITLE
Add a recurring class: `add -cr [CLASS_NAME] -d [START_DATE] -t [START_TIME] -p [DURATION_OF_LESSON]`

### ISSUE THREAD

**Issue by jamesyeap** [AY2122S2-CS2103T-W11-3/tp#10]
As a user, I can add permanent classes to the list that I can assign students to so that I can have an overview of which classes students are attending.

**Comment by jamesyeap** [comment]
I think we should change the format to make it easier to parse, like #11

**Comment by nnmoq** [comment]
It would make it slower to type though.

**Comment by nnmoq** [comment]
We can make it a shortcut and use #11 as the initial implementation. What do the rest think? @AY2122S2-CS2103T-W11-3/developers
