### ISSUE TITLE
Add command `clear -f` to delete all students and lessons

### ISSUE THREAD

**Issue by jamesyeap** [AY2122S2-CS2103T-W11-3/tp#109]
if user types in `clear` only, the command will not be executed and a warning will be shown

TODO: change this to a user story

**Comment by Kidsnd274** [comment]
Clearing the student/lesson list does not clear the InfoPanel and student assignment

When using the clear command, and a student is selected, the student details remain on the screen.
The clear command doesn't unassign students from classes. (although clear is supposed to remove all lessons and classes)

![image](https://user-images.githubusercontent.com/1343896/159757472-b2937e57-8da4-47b6-aea6-d982e96444ce.png)

![image](https://user-images.githubusercontent.com/1343896/159757589-1e0116db-1cde-4188-8885-eaa51f8f7a53.png)
