### ISSUE TITLE
[PE-D] Edit student format message is wrong

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W11-3/tp#198]
Expected:
Should have spacing between prefix and parameters, and the meaning of [ ] should be stated in the UG or in the format message

Actual:
![image.png](https://raw.githubusercontent.com/tyanhan/ped/main/files/777da39a-0fb0-4af3-954d-0de72d966beb.png)

To reproduce:
Follow the command in the above image

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tyanhan/ped#7

**Comment by Kidsnd274** [comment]
Note: Specify in the UG that the square brackets are optional.
Update the message to add spacing between the prefixes
eg. [-n NAME]
