### ISSUE TITLE
[PE-D] Cannot see the lessons list and persons list at the same time

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W11-3/tp#207]
Cannot see the lessons list and persons list at the same time, makes it difficult to assign a lesson to a student because both the lesson index and person index is required. 

Causes a lot of inconvenience when assigning which seems like a key feature of the app.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: tyanhan/ped#10

**Comment by Kidsnd274** [comment]
Good point, however due to the feature freeze we can't change the UI anymore.
